server:
  port: 8081

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效

rpc:
  application:
    name: provider
  metadata-report:
    address: nacos://prod:8848
  registry:
    host: prod
    port: 8848
  consumer:
    timeout: 10000
    check: false
  provider:
    timeout: 5000
    port: 28081


log-out:
  dir-name: provider
  path: D:/my/logs
